import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import "../csscode/CustomerDashboard.css";

export default function CustomerDashboard() {
  const navigate = useNavigate();

  /* ================= STATE ================= */
  const [customer, setCustomer] = useState(null);
  const [bookings, setBookings] = useState([]);

  /* ================= PAGINATION ================= */
  const ITEMS_PER_PAGE = 3;
  const [currentPage, setCurrentPage] = useState(1);

  /* ================= STATUS ORDER ================= */
  const STATUS_PRIORITY = {
    confirmed: 1,
    pending: 2,
    "checked-in": 3,
    cancelled: 4,
  };

  /* ================= SORT + PAGINATE ================= */
  const sortedBookings = [...bookings].sort((a, b) => {
    const pa = STATUS_PRIORITY[a.status?.toLowerCase()] ?? 99;
    const pb = STATUS_PRIORITY[b.status?.toLowerCase()] ?? 99;
    return pa - pb;
  });

  const totalPages = Math.ceil(sortedBookings.length / ITEMS_PER_PAGE);

  const paginatedBookings = sortedBookings.slice(
    (currentPage - 1) * ITEMS_PER_PAGE,
    currentPage * ITEMS_PER_PAGE
  );

  /* ================= RESET PAGE ON DATA CHANGE ================= */
  useEffect(() => {
    setCurrentPage(1);
  }, [bookings]);

  /* ================= HELPERS ================= */
  const calculateNights = (checkIn, checkOut) => {
    const inDate = new Date(checkIn);
    const outDate = new Date(checkOut);
    return Math.max(1, Math.ceil((outDate - inDate) / (1000 * 60 * 60 * 24)));
  };

  const API_BASE = "http://localhost:5186";

  const getFirstImage = (imagePaths) => {
    if (!imagePaths) return "/placeholder-room.jpg";

    let imgPath = imagePaths;

    if (typeof imagePaths === "string" && imagePaths.trim().startsWith("[")) {
      try {
        imgPath = JSON.parse(imagePaths)?.[0];
      } catch {
        return "/placeholder-room.jpg";
      }
    }

    if (!imgPath) return "/placeholder-room.jpg";
    if (imgPath.startsWith("http")) return imgPath;

    return `${API_BASE}/${imgPath.replace(/^\/+/, "")}`;
  };

  /* ================= AUTH + DATA ================= */
  useEffect(() => {
    const stored = localStorage.getItem("customer");
    if (!stored) {
      navigate("/Customer-login");
      return;
    }

    const parsed = JSON.parse(stored);
    setCustomer(parsed);

    fetch(`http://localhost:5186/api/bookings/customer/${parsed.customerId}`)
      .then((res) => res.json())
      .then((data) => setBookings(data))
      .catch(() => console.error("Failed to load bookings"));
  }, [navigate]);

  if (!customer) return null;

  const handleLogout = () => {
    localStorage.removeItem("customer");
    navigate("/Customer-login");
  };

  /* ================= UI ================= */
  return (
    <div className="dashboard">
      <div className="dashboard-header">
        <div>
          <h2>Welcome, {customer.fullName}</h2>
          <p>
            {customer.email} | {customer.phone}
          </p>
        </div>

        <div style={{ display: "flex", gap: "12px" }}>
          <button
            className="btn-solid"
            onClick={() => navigate("/customer-landing")}
          >
            Home
          </button>
          <button onClick={handleLogout} className="btn-logout">
            Logout
          </button>
        </div>
      </div>

      <section className="dash-section">
        <h3>My Bookings</h3>

        {paginatedBookings.map((b) => {
          const nights = calculateNights(b.checkInDate, b.checkOutDate);
          const estimatedAmount = b.basePricePerNight * nights;

          return (
            <div key={b.bookingId} className="booking-card">
              <div className="booking-top">
                <img
                  src={getFirstImage(b.roomImages)}
                  alt={b.roomTypeName}
                  className="booking-room-img"
                />

                <div className="booking-info">
                  <div className="booking-row">
                    <strong>{b.roomTypeName}</strong>
                    <span className={`status ${b.status.toLowerCase()}`}>
                      {b.status}
                    </span>
                  </div>

                  <p>
                    {new Date(b.checkInDate).toLocaleDateString()} →{" "}
                    {new Date(b.checkOutDate).toLocaleDateString()}
                  </p>

                  <p>Guests: {b.guests}</p>

                  <p>
                    👤 Guest: <strong>{b.guestName}</strong> ({b.guestPhone})
                  </p>

                  <p className="price-estimate">
                    💰 Estimated Charges: PKR {estimatedAmount}
                  </p>

                  <p className="invoice-note">
                    🧾 Final invoice will be generated by the hotel.
                  </p>
                </div>
              </div>
            </div>
          );
        })}

        {totalPages > 1 && (
          <div className="pagination">
            <button
              disabled={currentPage === 1}
              onClick={() => setCurrentPage((p) => p - 1)}
            >
              ← Prev
            </button>

            <span>
              Page {currentPage} of {totalPages}
            </span>

            <button
              disabled={currentPage === totalPages}
              onClick={() => setCurrentPage((p) => p + 1)}
            >
              Next →
            </button>
          </div>
        )}
      </section>
    </div>
  );
}
